### ISSUE TITLE
Code for CUT: A Controllable, Universal, and Training-Free Visual Anomaly Generation Framework

### ISSUE THREAD

**Issue by ShileiZeng** [pjl1995/Awesome-Anomaly-Image-Generation#1]
CUT: A Controllable, Universal, and Training-Free Visual Anomaly Generation Framework对应的代码链接似乎并不是这篇文章的代码，这篇文章好像还没开源，作者大大可以check一下吗

**Comment by pjl1995** [comment]
Thanks for your reminder. This method is indeed not open-sourced. We have modified it.
